env: "local"

storage:
  database_url: "postgres://postgres:postgres@localhost:5432/postgres"

server:
  port: 8080

bot:
  token: "5790471717:AAGNWzn5g5apmzaBARgjJz5TCsQrZpru9ZI"
  timeout: 60
  debug: true

web_app:
  url: ""
  port: 8081

email:
  host: "smtp.bsu.by"
  port: 587
  username: ""
  password: ""
  from_email: ""
  from_name: "Quiz Platform"
  domain: "bsu.by"
  prefix: "rct."
  template_dir: "./templates/email"
  debug: false
