env: "local"

storage:
  database_url: "postgresql://postgres:HPUbGJXdRBchvtSdqaRBACkxzwhgFtdE@postgres.railway.internal:5432/railway"

server:
  port: 8080

bot:
  token: "5790471717:AAGNWzn5g5apmzaBARgjJz5TCsQrZpru9ZI"
  timeout: 60
  debug: false

web_app:
  url: ""
  port: 8081